name: ItemDisguiseMod
version: 1.0.0
description: Change the appearance of inventory items.
author: Comphenix
website: http://www.comphenix.net/ItemDisguise

main: com.comphenix.itemdisguise.ItemDisguiseMod
depends: [ProtocolLib]
database: false

commands:
   explosion:
      description: Creates a fake explosion around the caller.
      usage: /<command>